idf_component_register(SRCS "main.c"
                    INCLUDE_DIRS ".",
                    "/mnt/evenmorestuff/naukri_hustle/programming/esp_32/esp-idf/components/bt/include/esp32/include/esp_bt.h",
                    "/mnt/evenmorestuff/naukri_hustle/programming/esp_32/esp-idf/components/**")

                    
